---
- name: Deploy sample application into K8s.
  hosts: localhost
  vars:
    ansible_python_interpreter: '/usr/bin/python3'    # Forcing ansible to use Python3
  tasks:                                              # This task aims to create K8s namespace to deploy nginx to.
    - name: Create a k8s namespace.
      k8s:                                            # Using K8s collection
        name: nginx-app-namespace
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/tux/.kube/config
    - name: Deploy nginx app                          # Deploy nginx into EKS cluster within the created namespace using K8s Config file.
      k8s:
        src: /home/tux/devops-interview-project/nginx-app.yaml
        state: present
        kubeconfig:  /home/tux/.kube/config
        namespace: nginx-app-namespace
