---
- name: Deploy sample application into K8s.
  hosts: localhost
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: Create a k8s namespace.
      k8s:
        name: nginx-app-namespace
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/tux/.kube/config
    - name: Deploy nginx app
      k8s:
        src: /home/tux/devops-interview-project/nginx-app.yaml
        state: present
        kubeconfig:  /home/tux/.kube/config
        namespace: nginx-app-namespace